### ISSUE TITLE
Implement common margin props

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1792]
### Description

다양한 컴포넌트에서 사용할 수 있는 공용 margin prop을 구현합니다.

### Reasons for suggestion

> https://www.radix-ui.com/themes/docs/theme/layout#margin-props 에서 영감을 받았습니다.

margin 속성은 컴포넌트의 내부 스타일링(우리의 디자인 결정)에 영향을 미치는 속성이 아닙니다. 사용자 편의성을 위해서 일부 컴포넌트에서 margin을 쉽게 적용할 수 있는 속성을 지원하면 좋겠다고 판단했습니다. 이미 Text, Icon 컴포넌트에서 지원하고 있으며, 사용처에서 유용하게 사용되고 있습니다.

### Proposed solution

margin prop을 지원하는 컴포넌트는 다음 인터페이스를 준수해야합니다.

```tsx
interface MarginProps {
  m?: CSSProperties['margin']
  mx?: CSSProperties['margin']
  my?: CSSProperties['margin']
  mt?: CSSProperties['marginTop']
  mr?: CSSProperties['marginRight']
  mb?: CSSProperties['marginBottom']
  ml?: CSSProperties['marginLeft']
}
```

- 디자인 시스템에서 spacing 토큰을 사용하지 않으므로 유한한 값으로 타입을 제한하기는 어렵습니다.
- margin prop을 지원하는 컴포넌트의 root node에 CSS Variable을 통해 스타일을 적용합니다. 
- 해당 스타일을 쉽게 적용할 수 있는 헬퍼 함수의 구현이 추가로 필요할 거 같습니다. (see: https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/helpers/props/margin.props.ts)

```css
@layer components {
  .margin {
    --margin-all: var(--b-margin-all, 0);

    margin:
      var(--b-margin-top, var(--b-margin-y, var(--margin-all)))
      var(--b-margin-right, var(--b-margin-x, var(--margin-all)))
      var(--b-margin-bottom, var(--b-margin-y, var(--margin-all)))
      var(--b-margin-left, var(--b-margin-x, var(--margin-all)));
  }
}
```

- 기존 `Text`, `Icon` 컴포넌트에도 margin prop이 자체 구현되어있습니다. 이를 마이그레이션합니다. 마이그레이션 코드 작성이 필요할 수 있습니다.
- **shorthand(`m`)만 지원할지, 전체 이름(`margin`)으로도 지원할지 고민입니다. 둘의 우선순위를 판단하기가 어려워, 우선은 shorthand만 지원하는 쪽으로 결정했습니다.**

### References

- https://www.radix-ui.com/themes/docs/theme/layout#margin-props

<img width="784" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/922246e2-ccae-411f-90a4-c05b7943b717">
