### ISSUE TITLE
Prepare for breaking change of sass 

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2360]
### Description

sass 1.77.8에서 nested rule 다음에 unnested rule이 오는 syntax를 deprecated 처리 한다고 합니다. 메이저 버전이 올라갈 때를 대비하기 위해 미리 마이그레이션을 하면 좋을 듯 합니다. 

### Reasons for suggestion

> The use of declarations after nested rules is currently deprecated in Sass, in order to notify users of the upcoming change and give them time to make their stylesheets compatible with it. In a future release, Dart Sass will change to match the ordering produced by plain CSS nesting.

버전을 올리고 빌드하면 빌드 워닝이 뜹니다. 

<img width="609" alt="image" src="https://github.com/user-attachments/assets/04f8bac6-d501-4b94-9928-9a46a55f5a64">

### Proposed solution

문서에서 제안한 것처럼 & { } 로 감싸거나 순서를 변경합니다. 

### References

https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by theaniketnegi** [comment]
Is it okay to disable some lint rules? 🤔

**Comment by yangwooseong** [comment]
Yes you can disable them if necessary. 

How did you try to do migration? scss is elevating the unnested rule that follows the nested rule to the nested rule, so I thought it would be enough to simply change the order without wrapping with `${ }`.

```scss
// As-is
.example {
  color: red;

  a {
    font-weight: bold;
  }

  font-weight: normal;
}

// To-be
.example {
  color: red;
  font-weight: normal;

 a {
  font-weight: bold;
}
```
